home-assistant:
  ingress:
    enabled: true
    className: "traefik"
    annotations:
      cert-manager.io/cluster-issuer: jansen-ca-issuer
    hosts:
      - host: home-assistant.jansen.lan
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - home-assistant.jansen.lan
        secretName: home-assistant-tls
  

  resources:
    limits:
      akri.sh/akri-zbt-2: "1"
      akri.sh/akri-dsmr-p1-to-usb: "1"
    requests:
      akri.sh/akri-zbt-2: "1"
      akri.sh/akri-dsmr-p1-to-usb: "1"